export enum GENRES  {
    anime = "аниме",
    biography = "биография",
    action = "боевик",
    western = "вестерн",
    war = "военный",
    detective = "детектив",
    children = "детский",
    adult = "для взрослых",
    documentary = "документальный",
    drama = "драма",
    game = "игра",
    history = "история",
    comedy = "комедия",
    concert = "концерт",
    "short-film" = "короткометражка",
    crime = "криминал",
    melodrama = "мелодрама",
    music = "музыка",
    animation = "мультфильм",
    musical = "мюзикл",
    news = "новости",
    adventure = "приключения",
    family = "семейный",
    sport = "спорт",
    "talk-show" = "ток-шоу",
    thriller = "триллер",
    horror = "ужасы",
    "science-fiction" = "фантастика",
    "film-noir" = "фильм-нуар",
    fantasy = "фэнтези",
    ceremony = "церемония",
  };
  